name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: stardustdrive-dfbfe
        service_account_key: ${{ secrets.GCP_CREDENTIALS }}
        export_default_credentials: true

    - name: Build and Push to Cloud Build
      run: |
        gcloud builds submit --tag gcr.io/stardustdrive-dfbfe/stardustdrive

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy stardustdrive \
          --image gcr.io/stardustdrive-dfbfe/stardustdrive \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
